### ISSUE TITLE
Adding Litecoin and Dogecoin support

### ISSUE THREAD

**Issue by DaGitNah** [brighton36/CoinPost#5]
Hi, is there any way of adding litcoin and dogecoin support? I know this is specifically geared towards bitcoins, but why not other coins?

**Comment by brighton36** [comment]
That wouldn't be too hard to add at all. Most of the stubs needed to support that are in place.

**Comment by DaGitNah** [comment]
Do you charge sellers fees for using the marketplace? if not can that be added?

**Comment by brighton36** [comment]
We do not - and yes it can!
